// LOGGER CONSTANTS
export const CLUSTER_LOGGER = 'CLUSTER'
export const DATABASE_LOGGER = 'DATABASE'
export const CREATE_USER_USE_CASE_LOGGER = 'CREATE_USER_USE_CASE'
export const GET_ALL_USERS_USE_CASE_LOGGER = 'GET_ALL_USERS_USE_CASE'
export const GET_ALL_NOTIFICATIONS_USE_CASE_LOGGER = 'GET_ALL_NOTIFICATIONS_USE_CASE'
export const UDPATE_DISCOUNT_PERCENTAGE_USE_CASE_LOGGER = 'UDPATE_DISCOUNT_PERCENTAGE_USE_CASE'
export const CREATE_NOTIFICATION_USE_CASE_LOGGER = 'CREATE_NOTIFICATION_USE_CASE'
export const APPLY_DISCOUNT_TO_USER_USE_CASE_LOGGER = 'APPLY_DISCOUNT_TO_USER_USE_CASE'
export const EXPRESS_API_LOGGER = 'EXPRESS_API'
export const PUBSUB_LOGGER = 'PUBSUB'

// PUBSUB CONSTANTS
export const USER_CREATED_EVENT = 'USER_CREATED'
